version: '3.8'

services:
  # Service API Node.js
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongodb:27017/propelize_db
      - JWT_SECRET=your-super-secret-jwt-key-change-in-production
      - JWT_EXPIRES_IN=15m
      - JWT_REFRESH_SECRET=your-super-secret-refresh-key-change-in-production
      - JWT_REFRESH_EXPIRES_IN=7d
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - propelize-network

  # Service MongoDB
  mongodb:
    image: mongo:6.0
    container_name: propelize_mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: propelize_db
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    networks:
      - propelize-network

  # Service MongoDB Express (Interface d'administration)
  mongo-express:
    image: mongo-express:latest
    container_name: propelize_mongo_express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
    depends_on:
      - mongodb
    networks:
      - propelize-network

volumes:
  mongodb_data:

networks:
  propelize-network:
    driver: bridge

# Dockerfile
